
services:
  app:
    build:
      context: ./fasad
    container_name: facade_app
    command: >
      sh -c "uvicorn fasad.main:app --host 0.0.0.0 --port 5005 --reload & 
              python -m fasad.bot.bot"
    ports:
      - 5005:5005
    networks:
      - mynetwork

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Убедитесь, что путь правильный
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - mynetwork

  certbot:
    image: certbot/certbot  # Исправленный отступ
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx
    entrypoint: "/bin/sh -c 'certbot certonly --nginx --email facadecontinent@gmail.com --agree-tos --no-eff-email -d facade-continent.ru -d www.facade-continent.ru && trap exit TERM; while :; do certbot renew; sleep 12h & wait ${!}; done;'"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


