services:
  app:
    build:
      context: ./fasad
    container_name: facade_app
    command: >
      sh -c "uvicorn fasad.main:app --host 0.0.0.0 --port 5005 --reload & 
              python -m fasad.bot.bot"

    ports:
      - 5005:5005  # Добавьте эту строку
    networks:
      - mynetwork


  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Убедитесь, что путь правильный
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
