global:
  scrape_interval: 10s

  external_labels:
    monitor: 'facade_app.py'


scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'facade_stat'

    dns_sd_configs:
      - names: ['facade_app.py']
        port: 5001
        type: A
        refresh_interval: 5s